.github/ISSUE_TEMPLATE/bug_report.md
There was an issue with the previous bug_report.md, it wasn't getting preloaded like the other two templates. Merging this PR will fix that.
Fixes #5 
- Code
- User Interface
- Outreach
=> docs: Fix bug_report.md

docs/code_of_conduct.md, docs/contributing_guidelines.md, docs/reporting_guidelines.md
the user needs to know the code of conduct, contributing guidelines and reporting guidelines before starting to contribute to the repository
Fixes #11 
- This change requires a documentation update (software upgrade )
=> "add a folder containing code of conduct and guidelines"

app/apis/__init__.py, app/apis/author.py, app/apis/models/author.py, app/apis/validations/author.py, app/database/models/author.py, app/utils/messages.py
Added POST Author api endpoint
Fixes #15 
- Code
Tested via Swagger UI
=> feat: Added author POST endpoint

README.md
update readme.md
Fixes #8
Delete irrelevant options.
Code/Quality Assurance Only
This change requires a documentation update (software upgrade on readme file)
Delete irrelevant options.
My PR follows the style guidelines of this project
I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
I have made corresponding changes to the documentation
Any dependent changes have been merged
Code/Quality Assurance Only
My changes generate no new warnings
=>  create description of README.md

app/database/models/videos.py
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
Fixes #25 
- Code
Tested on local machine
=> feat: Added preview url in video table

README.md
Added instructions to setup backend environment setup as mentioned in wiki
Fixes #29 
=> Update readme with backend setup instriuctions

app/apis/video.py, app/database/models/users.py
Add User table to database.
Add User table which contains:
**USERS TABLE**
|Key   |Type   |
|---|---|
|id | INTEGER | NOT | NULL|
|name | VARCHAR(30)  | 
|username | VARCHAR(30)  | 
|email | VARCHAR(30)  | 
|password_hash | VARCHAR(100)  | 
|registration_date | INT  | 
|terms_and_conditions_checked | BOOLEAN  | 
|access_rights | INT  | 
|is_email_verified | BOOLEAN  | 
|email_verification_date | INT |
Fixes #26
- Code
Locally - table has been generated.
=> feat: Add users table to database

run.py
Updated file name in order to use build pack on Heroku for google credentials json file
Fixes #38
=> updated file name for google credentials

app/apis/video.py, app/database/models/category.py
Add Category endpoint
Fixes #19 
- Code
SwaggerUI
=> feat: Add category endpoint

app/apis/author.py, app/apis/middlewares/auth.py, app/apis/section.py, app/apis/video.py, app/utils/messages.py
Add authorization middleware that will check every request - token presence and it's validity. Returns 401 if the token is invalid.
Fixes #47.
- Code
Tested through Swagger UI.
=> feat: Add authorization middleware

app/apis/__init__.py, app/apis/category.py, app/apis/video.py
Moved subroute  `/video/add_category` to its own endpoint `/category` separated from the video endpoint.
Closes #53 
- Code
Tested locally through swagger UI
=> Fix: move /video/add_category to /category endpoint

app/api/controllers/author.py, app/api/controllers/category.py, app/api/mappers/author_mapper.py, app/api/mappers/section_mapper.py
Changed multiple line for loops into lambda expressions. 
Fixes #67 
- Code
Tested through Swagger UI and all the changed code is functioning similarly as before.
=> Refactor: Refactor code to use lambda expressions

app/api/controllers/category.py, app/api/dao/category_dao.py, app/database/models/category.py
Added endpoint for removing an existing category.
Fixes #70 
- Code
Tested locally through Swagger UI
=> feat: Add Delete Category Endpoint

app/api/controllers/section.py, app/api/dao/section_dao.py, app/database/models/category.py, app/database/models/section.py, app/utils/messages.py
Added endpoint for section removal. If the section does not exist, `NOT FOUND` is returned. Fixes #69.
- Code
Tested through Swagger UI:
- Case 1: success
- Case 2: non-existing section
=> Feat: Add delete section endpoint

app/api/controllers/category.py, app/api/models/video.py
Add get all sections endpoint for given category id with authentication.
Fixes #56 
- Code
Tested the GET all sections endpoint on Swagger UI.
=> Feat : Add GET all sections endpoint for given category id with authentication

app/api/controllers/__init__.py, app/api/controllers/feed.py, app/api/controllers/video.py, app/api/mappers/feed_mapper.py, app/api/mappers/video_mapper.py, app/utils/messages.py
Implemented an endpoint that takes section id and returns the feed of the video data. Fixes #13.
URL: `/feed/?section_id=`
- Code
Tested through Swagger UI:
- Case 1: section id is not provided at all
- Case 2: section does not exist
- Case 3: successful
Example JSON:
```json
{
"type": {
"value": "feed"
},
"id": 7,
"title": "section example title",
"media_group": [],
"entry": [
{
"author": {
"name": ""
},
"type": {
"value": "video"
},
"id": 2,
"title": "The Future of STEM Depends on Diversity | Nicole Cabrera Salazar | TEDxGeorgiaStateU",
"summary": null,
"published": "2015-06-30 00:00:00",
"updated": "2015-06-30 00:00:00",
"content": {
"src": "https://r3---sn-ncc-cxbz.googlevideo.com/videoplayback?expire= …
```
=> feat: Add section feed endpoint

app/api/controllers/feed.py, app/api/mappers/video_mapper.py
Include regular mp4 videos (non-YT) videos to the feed based on the section. Content URL in that case is the same as the origin URL. Fixes #95. 
- Code
Tested manually through Swagger UI. One instance of mp4 video in the feed:
```json
{
"author": {
"name": "test, test2, test3"
},
"type": {
"value": "video"
},
"id": 4,
"title": "video_example",
"summary": null,
"published": "2020-10-10 00:00:00",
"updated": "2020-10-10 00:00:00",
"content": {
"src": "https://sec.ch9.ms/ch9/3ce8/7b1866c4-a58e-44b0-bc70-7d27e8613ce8/BDL213_high.mp4",
"type": "video/hls"
},
"link": {
"type": "link",
"href": ""
},
"media_group": [
{
"type": "image",
"media_item": [
{
"key": "image_base",
"src": …
```
=> Feat: Include regular mp4 videos to the video feed

.env.template, README.md, config.py, requirements.txt, run.py
Added configuration of environments: `local, dev, stage, test and production` with an apporatiate configuration setup. Enabled persistent database connection and update the documentation with the instructions on database setup. Fixes #105 
- Code
Tested through Swagger UI and DBMS (PostgreSQL).
- [] Any dependent changes have been merged
Note: There are things that need to be changed when Postgres is used.
=> Feat: Add environment configuration modes and enable persistent database settings

app/api/controllers/video.py, app/api/dao/video_dao.py
Added delete video endpoint
Fixes #102 
- Code
Through swagger UI
=> feat: Add delete video endpoint

.env.template, .gitignore, README.md, app/api/dao/user_dao.py, app/utils/email_utils.py, app/utils/mail_extension.py, requirements.txt, run.py, templates/email_confirmation.html
Implemented email services for the CMS. 
I have added sending verification link service and also implemented a generic send email function which can be used for any kind of email service.  
Also added a html template which will be send to email address of the user
Fixes #92 
- Code
Tested on development server. 
=> feat: Email service

app/database/models/author.py, app/database/models/category.py, app/database/models/section.py, app/database/models/users.py, app/database/models/video.py
Added database constraints (mostly unique constraints). Fixes #83.
- Code
- Bugfix (non-breaking change which fixes an issue)
Tested through the process of adding entries that violate added constraints (with turning-off validations we currently have).
=> Bugfix: Added database constraints

.gitignore, README.md
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
Fixes # [Bug: Update README with the additional instructions for the firebase setup #46]
Not Applicable
=> fix: Correct filename for credentials file in readme.md and .gitignore

app/database/models/users.py
Change the data type of the registration column to datetime. Fixes #109.
- Code
Tested through Swagger UI.
=> Bug: Change registration date type to datetime

Dockerfile, Makefile, docker-compose.test.yml, docker-compose.yml
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
Fixes #125  
- Code
=> feat: Docker support

run.py
This should fix the cors error we're getting on the frontend.
- Code
- Bugfix (non-breaking change which fixes an issue)
=> fix: Cors origin url

README.md
Removed Table of contents from Readme file, as now with the GitHub UI, project have a dropdown list for table of contents
Fixes #147 
=> Removed table of contents from Readme

.all-contributorsrc, README.md
- Create all-contributors configuration file.
- Add contributors section to README.
Fixes #188 
- Code
I followed this example which I used before in all the other active repositories: https://github.com/anitab-org/mentorship-android/pull/1114/files
After merge you can run the command on any comment, can be this PR or on an issue.
```
@all-contributors please add @annabauza for code, maintenance, test, doc and design
```
The documentation shows the available tags. the bot will then create a PR to add you to JSON config and README.
=> chore: setup all-contributors bot

README.md
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
Fixes #216 
BEFORE 
AFTER CHANGES 
- Code
- User Interface
- Outreach
=> added badge and link

docusaurus.config.js
Fixed the edit URL for the docusauras pages.
Fixes #215 
=> fix: Docusauras editUrl

README.md
Removed the redundancy of the heading in the Readme file
Fixes #143
Previewed the readme file
=> Removed the redundancy of headings in Readme file

docusaurus.config.js, src/pages/index.js
The tagline of the project has been updated to the project name and the unnecessary icons have been removed. Updated the Copyright of the project to Copyright © 2021 AnitaB.org
Fixes #217 
=> Docs: Update the documentation of the project on Docusauras, fixes issue #217

README.md
Added Badges of Javascript, Python, HTML on a readme.md file
Fixes #138 
- Code
- User Interface
- Outreach
=> Added Javascript, Python, HTML badges

docs/home.md
Grammatically updated the docs on the home page.
Fixes # [ISSUE]
=>  Docs: Updated Documentation text 

docs/contributing_guidelines.md
Incorrect link to bug report in the Contributing Guidelines file
Fixes #128 
=> docs:Update docs, fixes issue #128

app/api/controllers/category.py, app/api/dao/category_dao.py
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change. 
use category dao to fetch all categories
Fixes #134 
- Code
=> bug: use category dao to fetch all categories

README.md
Added versions for frameworks and languages used, in readme.md file
Fixes #141 
Added Versions for flask and its frameworks used in the project.
- [✓ ] My PR follows the style guidelines of this project
- [ ✓] I have performed a self-review of my own code or materials
- [ ✓] I have made corresponding changes to the documentation
- [ ✓] Any dependent changes have been merged
- [ ✓] New and existing unit tests pass locally with my changes
=> Added versions for frameworks/languages
